services:
  frontend:
    container_name: frontend
    build: ./frontend
    command: python ./frontend/frontend.py
    ports:
      - "3000:3000"
    volumes:
    links:
      - db
  backend:
    container_name: backend
    build: ./backend
    volumes:
    ports:
      - "3001:3000"
  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
