name: App CD

on: 
  pull_request:
    branches: [ main ]

  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          cd app
          pytest
  docker: 
    needs: build
    defaults:
      run:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Build and push
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          uses: docker/build-push-action@v3
          with:
            context: ./app

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      -
        name: DigitalOcean App Platform Deployment
        uses: digitalocean/app_action@main
        with:
            app_name: bookshare-app
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}