name: Build Image/CD

on: 
  pull_request:
    branches: ['main']

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: saraha/bookshare:latest

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-app

    steps:
    - name: DigitalOcean Platform Deployment
      uses: digitalocean/app_action@main
      with:
        app_name: bookshare
        token: ${{ secrets.DIGITALOCEAN_API_KEY  }} 
    