name: App CD

on: 
  pull_request:
    branches: ['main']

  push: 
    branches: ['main']

jobs:
  docker: 
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Build and push
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          uses: docker/build-push-action@v3
          with:
            context: ./app

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      -
        name: DigitalOcean App Platform Deployment
        uses: digitalocean/app_action@main
        with:
            app_name: bookshare-app
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}