name: App CD

on: 
  pull_request:
    branches: [ main ]

  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest

  dockerhub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: build
      defaults:
        run:
          working-directory: ./app
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and Push
          run: |
            docker build . --tag sarahaltowaity1/bookshare
            docker push sarahaltowaity1/bookshare

    deploy:
      runs-on: ubuntu-latest
      needs: dockerhub
      steps:
        - name: DigitalOcean App Platform deployment
          uses: digitalocean/app_action@main
          with:
            app_name: bookshare-app
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}